<?
// This page appears to the browser as an image file containing the specified team's page background.
// Include only the essentials. Don't start a session here - it causes a big hit on Windows/IIS servers
define("SHAREDBASE_DIR", $_SERVER["DOCUMENT_ROOT"] . "/Shared/");
require(SHAREDBASE_DIR . "DBConnection.php");
require(SHAREDBASE_DIR . "EnableCache.php");    // allow browser to cache image generated by this page
require(dirname(__FILE__) . "/../script/data-helpers.php");
require(dirname(__FILE__) . "/../script/defaults.php");

$oDB = oOpenDBConnection();
$teamID = intval($_REQUEST['T']);
$organizationID = $oDB->DBLookup("OrganizationID", "teams", "TeamID=$teamID", 1);

$rs = $oDB->query("SELECT BodyBGColor, BodyImage FROM teams WHERE TeamID=$teamID", __FILE__, __LINE__);
if(($record = $rs->fetch_array())==false || (is_null($record['BodyImage']) && (is_null($record['BodyBGColor']) || $record['BodyBGColor']==BODY_BG_COLOR)))
{
    // default background image depends on team type
    $bgFile = ($organizationID==2) ? "tdot.gif" : "ridenetbg.jpg";
    // This team has not customized their background color / background image yet
    $picData=file_get_contents(dirname(__FILE__) . "/../images/$bgFile");
    header("Content-type: image/jpeg");
    echo $picData;
}
elseif(!is_null($record['BodyImage']))
{
    // display page background from database
    header("Content-type: image/jpeg");
    echo $record['BodyImage'];
}
else
{
    // This team does not have a page background. Return a blank image (background color will show through)
    $picData=file_get_contents(dirname(__FILE__) . "/../images/tdot.gif");
    header("Content-type: image/gif");
    echo $picData;
}
?>