<?
// This page appears to the browser as an image file containing the specified team's page banner.
// Include only the essentials. Don't start a session here - it causes a big hit on Windows/IIS servers
define("SHAREDBASE_DIR", $_SERVER["DOCUMENT_ROOT"] . "/Shared/");
require(SHAREDBASE_DIR . "DBConnection.php");
require(SHAREDBASE_DIR . "EnableCache.php");    // allow browser to cache image generated by this page
require(SHAREDBASE_DIR . "SimpleImage.php");
require(dirname(__FILE__) . "/../script/data-helpers.php");

$oDB = oOpenDBConnection();
$teamID = intval($_REQUEST['T']);
$teamTypeID = $oDB->DBLookup("TeamTypeID", "teams", "TeamID=$teamID", 1);

ob_start();   // buffer the output so it's sent as a single chunk
$rs = $oDB->query("SELECT HomePageImage FROM teams WHERE TeamID=$teamID AND HomePageImage IS NOT NULL", __FILE__, __LINE__);
if(($record = $rs->fetch_array())!=false)
{
    // display homepage image from database
    header("Content-type: image/jpeg");
    echo $record['HomePageImage'];
}
else
{
    // default homepage image depends on the team type (hard-code for now)
    if($teamTypeID==2)
    {
        // image for 2BY2012 pages
        $imageFile = "2by2012-homepage.jpg";
    }
    else
    {
        // banner for ridenet teams depends on weather team is showing logo in the center of the banner
        $imageFile = "ridenet-homepage.jpg";
    }
    // This team does not have a homepage image. Display default banner
    $picData=file_get_contents(dirname(__FILE__) . "/../images/$imageFile");
    header("Content-type: image/jpeg");
    echo $picData;
}
header("Content-Length: " . ob_get_length());   // tell the browser the size of the image
ob_end_flush();                                 // flush and close buffer
?>