<?
// This page appears to the browser as an image file containing the specified rider's picture.
// Note that the rider picture is dependent on the team of the rider. This allows a rider to
// change teams and upload a new photo without affecting their old race reports. The photo
// on the race report shows the team and picture of the rider at the time the report was filed

// Include only the essentials. Don't start a session here - it causes a big hit on Windows/IIS servers
require("../script/app-master-min.php");
require(SHAREDBASE_DIR . "EnableCache.php");    // allow browser to cache image generated by this page

$oDB = oOpenDBConnection();
$riderID = intval($_REQUEST['RiderID']);
$teamID = intval($_REQUEST['T']);

ob_start();   // buffer the output so it's sent as a single chunk
$rs = $oDB->query("SELECT Picture FROM rider_photos WHERE RiderID=$riderID AND TeamID=$teamID", __FILE__, __LINE__);
if(($record = $rs->fetch_array())!=false && ($record['Picture']!=""))
{
    // display rider picture from database
    header("Content-type: image/jpeg");
    echo $record['Picture'];
}
else
{
    // This rider has not uploaded a picture for this team. Display "unavailable" picture
    $picData=file_get_contents(dirname(__FILE__) . "/../images/picture-unavailable.jpg");
    header("Content-type: image/jpeg");
    echo $picData;
}
header("Content-Length: " . ob_get_length());   // tell the browser the size of the image
ob_end_flush();                                 // flush and close buffer
?>