<?
// This page appears to the browser as an image file containing the specified rider's picture.
// Note that the rider picture is dependent on the team of the rider. This allows a rider to
// change teams and upload a new photo without affecting their old race reports. The photo
// on the race report shows the team and picture of the rider at the time the report was filed

// Include only the essentials. Don't start a session here - it causes a big hit on Windows/IIS servers
define("SHAREDBASE_DIR", $_SERVER["DOCUMENT_ROOT"] . "/Shared/");
require(SHAREDBASE_DIR . "DBConnection.php");
require(SHAREDBASE_DIR . "EnableCache.php");    // allow browser to cache image generated by this page
require(dirname(__FILE__) . "/../script/data-helpers.php");

$oDB = oOpenDBConnection();
$riderID = intval($_REQUEST['RiderID']);
$teamID = intval($_REQUEST['T']);

$rs = $oDB->query("SELECT Picture FROM rider_photos WHERE RiderID=$riderID AND TeamID=$teamID", __FILE__, __LINE__);
if(($record = $rs->fetch_array())!=false && ($record['Picture']!=""))
{
    // display rider picture from database
    header("Content-type: image/jpeg");
    echo $record['Picture'];
}
else
{
    // This rider has not uploaded a picture for this team. Display "unavailable" picture
    $picData=file_get_contents(dirname(__FILE__) . "/../images/picture-unavailable.jpg");
    header("Content-type: image/jpeg");
    echo $picData;
}
?>